name: Terraform Destroy

on:
  push:
    branches:
      - destroy/*

env:
  AWS_REGION: us-east-1
  TF_VER: 1.3.0
  WORKING_DIR: ./network

jobs:
  tf-plan:
    name: 'terraform: init,validate,plan'
    runs-on: ubuntu-latest
    environment: dev-apply

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Add profile credentials to ~/.aws/credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile default
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile default
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "${{ env.TF_VER }}"

      - name: terraform init
        run: |
          cd "${{ env.WORKING_DIR}}"
          terraform init -input=false

      - name: terraform validate
        run: |
          cd "${{ env.WORKING_DIR}}"
          terraform validate

      - name: terraform destroy
        run: |
          cd "${{ env.WORKING_DIR}}"
          terraform destroy -auto-approve